server:
  port: 8081
spring:
  application:
    name: "GGastos"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: "local"
  data:
    mongodb:
      uri: "mongodb://mongo:nUelrKhespUDYGIYMCqQTkBIamFvnRuT@mongodb.railway.internal:27017"
      database: "mongo"
      auto-index-creation: true
jwt:
  secret: "${JWT_SECRET:BU4B1nghWq7ddqXkVeJD_seguro_para_jwt_de_32_caracteres}"
email:
  username: "${EMAIL_NAME:yeridstickramirez@gmail.com}"
  password: "${PASSWORD_EMAIL:hzxx rvww ncht qyfq}"
security:
  admin:
    email: "${ADMIN_EMAIL:ejemploadmin@gmail.com}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://gastosreactvite-production.up.railway.app/,http://localhost:3000/,https://gastosreactvite-production.up.railway.app/,http://192.168.80.26:3000/"